### ISSUE TITLE
page apporteurs d'affaires - créer page

### ISSUE THREAD

**Issue by Vin-CC** [Vin-CC/menelas_erp#16]
### TODO
- [x] créer la page dashboard sur l'url : /charges-affaire
- [x] créer endpoint /api/bussinessprovider GET
- [x] il doit être possible d'envoyer en queryparam un nom de chargé d'affaire pour récupérer une liste de chargé d'affaires dont l'identité correspond (au maximum 5)

### INFORMATIONS
- utiliser cette maquette : https://www.figma.com/proto/EYrM1LnYB3VN3D64k3VQGf/Menelas---ERP?t=C6Bfr5zdSXp9UNui-1
- utiliser les composants présents dans https://ui.shadcn.com/ et aucune autre librairie de composant
- utiliser les icons de feather ui présentes dans react icons
- la recherche doit fonctionner comme celle présente dans Genipatient mais en respectant l'UI/UX présente dans la maquette Ménélas
- les données sont récupérées avec fetch() (il faut donc créer un endpoint API, voir plus bas)
- le fetch doit contenir un tag
- prendre en compte les éventuelles remarques sur la maquette (post-it jaune)

### RÈGLES ENDPOINTS
- les endpoints doivent être protégés pour n'être accessible qu'aux utilisateurs connectés
- l'endpoint doit renvoyer un résultat paginé utilisant la méthode Keyset Pagination
- si le state envoyé en queryparam alors renvoyé l'erreur http pour une requête mal formatée

### FORMAT REQUÊTE ENDPOINTS
exemples formats possibles, ils peuvent être combinés :
```
/api/bussinessprovider
```
```
/api/bussinessprovider?search=identite+bussiness+provider
```
```
/api/bussinessprovider?last_seen_id=10&limit=10
```

### FORMAT RETOUR ENDPOINTS
La réponse du endpoint doit ressembler à ça:
```json
{
  "data": [le tableau de données],
  "meta": {
    "limit": 10,
    "last_seen_id": 10,
    "next_page": "/api/bussinessprovider?limit=10&last_seen_id=10",
    "prev_page": "/api/bussinessprovider?limit=10&last_seen_id=10",
    "current_page": 2,
    "max_page": 5,
    "total": 50
  }
}
```
