### ISSUE TITLE
Ajouter authentification (page login + google auth)

### ISSUE THREAD

**Issue by Vin-CC** [Vin-CC/menelas_erp#2]
### TODO
- [x] créer la page d’authentification sur l'url : /login
- [x] il doit être possible de toggle le dark et light mode pour les composants et pages
- [x] l'authentification doit être fonctionnelle

### INFORMATIONS
- utiliser cette maquette : https://www.figma.com/proto/EYrM1LnYB3VN3D64k3VQGf/Menelas---ERP?t=C6Bfr5zdSXp9UNui-1
- utiliser les composants présents dans https://ui.shadcn.com/ et aucune autre librairie de composant.
- reprends les valeurs du .env de Genipatient concernant le service mail
- doc dark mode: https://ui.shadcn.com/docs/dark-mode/next

### SCENARIO DE TEST
- Si l'utilisateur tente d'accéder à / sans être connecté il est redirigé vers /login
- Lorsque l'utilisateur est connecté et tente d'accéder à /login il est redirigé vers /
