### ISSUE TITLE
page assurés - créer page

### ISSUE THREAD

**Issue by Vin-CC** [Vin-CC/menelas_erp#4]
### TODO
- [x] créer la page assurés sur l'url : /assure
- [x] créer endpoint /api/policyholder GET
- [x] il doit être possible d'envoyer en queryparam un nom de projet pour récupérer une liste des assurés

### INFORMATIONS
- utiliser cette maquette : https://www.figma.com/proto/EYrM1LnYB3VN3D64k3VQGf/Menelas---ERP?t=C6Bfr5zdSXp9UNui-1
- utiliser les composants présents dans https://ui.shadcn.com/ et aucune autre librairie de composant
- utiliser les icons de feather ui présentes dans react icons
- la recherche doit fonctionner comme celle présente dans Genipatient mais en respectant l'UI/UX présente dans la maquette Ménélas (c'est à dire que la recherche ne doit pas être faite à chaque saisie d'un caractère mais après un temps une fois que le dernier caractère a été saisie)
- les données sont récupérées avec fetch() (il faut donc créer un endpoint API, voir plus bas)
- le fetch doit contenir un tag pour être reset plus tard lors de l'ajout de nouveaux assurés
- prendre en compte les éventuelles remarques sur la maquette (post-it jaune)

### RÈGLES ENDPOINTS
- les endpoints doivent être protégés pour n'être accessible qu'aux utilisateurs connectés
- l'endpoint doit renvoyer un résultat paginé utilisant la méthode Keyset Pagination

### FORMAT REQUÊTE ENDPOINTS
exemple de format de requêtes, ils peuvent être fusionnés :
```
/api/policyholder
```
```
/api/policyholder?search=nom+assure
```
```
/api/policyholder?last_seen_id=10&limit=10
```

### FORMAT RETOUR ENDPOINTS
La réponse du endpoint doit ressembler à ça:
```json
{
  "data": [le tableau de données],
  "meta": {
    "limit": 10,
    "last_seen_id": 10,
    "next_page": "/api/policyholder?limit=10&last_seen_id=20",
    "prev_page": "/api/policyholder?limit=10&last_seen_id=1",
    "current_page": 2,
    "max_page": 5,
    "total": 50
  }
}
```
