### ISSUE TITLE
page contrats - créer page

### ISSUE THREAD

**Issue by Vin-CC** [Vin-CC/menelas_erp#6]
### TODO
- [x] créer la page dashboard sur l'url : /contract
- [x] créer endpoint /api/contracts GET
- [x] il doit être possible d'envoyer en queryparam avec un nom de contrat pour récupérer une liste de contrats dont les noms correspondent
- [x] il doit être possible d'envoyer un queryparam avec un état (state), celui ci doit présent dans les valeurs de l'enum associé au state pour récupérer une liste de contrats
- [x] il doit être possible d'envoyer un queryparam avec l'id d'un user (souscripteur) pour récupérer une liste de contrats

### INFORMATIONS
- utiliser cette maquette : https://www.figma.com/proto/EYrM1LnYB3VN3D64k3VQGf/Menelas---ERP?t=C6Bfr5zdSXp9UNui-1
- utiliser les composants présents dans https://ui.shadcn.com/ et aucune autre librairie de composant
- utiliser les icons de feather ui présentes dans react icons
- la recherche doit fonctionner comme celle présente dans Genipatient mais en respectant l'UI/UX présente dans la maquette Ménélas
- les données sont récupérées avec fetch() (il faut donc créer un endpoint API, voir plus bas)
- le fetch doit contenir un tag pour être 
- prendre en compte les éventuelles remarques sur la maquette (post-it jaune)

### RÈGLES ENDPOINTS
- les endpoints doivent être protégés pour n'être accessible qu'aux utilisateurs connectés
- l'endpoint doit renvoyer un résultat paginé utilisant la méthode Keyset Pagination
- si le state envoyé en queryparam alors renvoyé l'erreur http pour une requête mal formatée

### FORMAT REQUÊTE ENDPOINTS
exemples formats possibles, ils peuvent être combinés :
```
/api/contracts
```
```
/api/contracts?search=nom+de+contrat
```
```
/api/contracts?last_seen_id=10&limit=10
```
```
/api/contracts?last_seen_id=10&limit=10&manager_id=10234
```

### FORMAT RETOUR ENDPOINTS
La réponse du endpoint doit ressembler à ça:
```json
{
  "data": [le tableau de données],
  "meta": {
    "limit": 10,
    "last_seen_id": 10,
    "next_page": "/api/contracts?limit=10&last_seen_id=10",
    "prev_page": "/api/contracts?limit=10&last_seen_id=10",
    "current_page": 2,
    "max_page": 5,
    "total": 50
  }
}
```
